/**
 * presentation-gate.corpus.ts — stress-corpus spec fixtures (C5, Wave 3;
 * design-2 §7.3). Single source consumed by the unit tests (Wave 3) and by
 * D2's e2e gate run (Wave 4).
 *
 * REGENERATED by Wave-4b (MUST-FIX 1): `expect` now pins the ACTUAL
 * post-wiring pipeline outcome — buildSceneGraph (deterministic layout pass)
 * → runGeometryGate → checkScene — computed on the production path the
 * renderer runs at setSpec (presentation/pipeline.ts is the gate's only
 * production call site). The Wave-3 expectations described a pipeline
 * that did not exist (7/10 contradicted the real output); every case below
 * was re-measured against the wired pipeline and is asserted exactly by
 * `tests/demonstrations/renderer/presentation-pipeline.test.ts` and
 * `tests/demonstrations/renderer/primitive-3d/presentation/pipeline.test.ts`.
 * Where the pinned outcome is an accepted limitation, `documentedLimitation`
 * carries the rationale (the gate still fails loudly — `gate_unverified` —
 * it never passes silently).
 *
 * The Wave-3 unit tests (geometry-gate.test.ts) assert the GATE-level
 * behavior on scenes derived from these fixtures (raw I1 envelope math, I4
 * head geometry) — those raw-geometry assertions are independent of this
 * regeneration.
 */

import { SPEC_LIMITS } from "@/demonstrations/spec/demo-spec";
import type { DemoSpecV1, PrimitiveObjectSpec } from "@/demonstrations/spec/demo-spec";

type Scene3D = NonNullable<DemoSpecV1["scene3d"]>;

export interface StressCorpusCase {
  id: string;
  spec: DemoSpecV1;
  expect: {
    critical: number;
    major: number;
    minor: number;
    /** Every listed reason must appear in the gate violations OR the
     * pipeline reasons (buildSceneGraph + placement + gate codes). */
    reasons: string[];
  };
  /** Accepted-limitation rationale for the pinned outcome (MUST-FIX 1). */
  documentedLimitation?: string;
}

/** Minimal valid spec shell (pattern shared with the accessible-diagram tests). */
export function makeSpec(
  id: string,
  objects: PrimitiveObjectSpec[],
  relationships: Scene3D["relationships"] = [],
  animations: Scene3D["animations"] = []
): DemoSpecV1 {
  return {
    schemaVersion: 1,
    id,
    generationId: `gen-${id}`,
    userQuery: `stress corpus: ${id}`,
    normalizedConcept: `stress corpus: ${id}`,
    title: `Stress corpus: ${id}`,
    learningObjective: "Exercise the geometry gate.",
    trust: {
      level: "conceptual_demonstration",
      label: "Conceptual demonstration",
      limitations: [],
    },
    renderer: {
      kind: "primitive_3d",
      fallbackKind: "accessible_diagram",
      preferredAspectRatio: 4 / 3,
      background: "dark",
    },
    scene3d: { objects, relationships, animations },
    controls: [],
    prediction: { prompt: "?", options: ["a", "b"] },
    observationPrompts: [],
    representations: [],
    adaptationContext: { allowed: false, oneVariableMode: true },
    provenance: {
      source: "template_composition",
      templateIds: [],
      generatedAt: "2026-08-08T00:00:00Z",
    },
    limits: {
      maxObjects: SPEC_LIMITS.maxObjects,
      maxParticles: SPEC_LIMITS.maxParticlesDesktop,
      maxTimelineEvents: SPEC_LIMITS.maxTimelineEvents,
      maxControls: SPEC_LIMITS.maxControls,
    },
  };
}

const sphere = (
  id: string,
  x: number,
  y: number,
  z = 0,
  size = 1,
  label?: string
): PrimitiveObjectSpec => ({
  id,
  kind: "sphere",
  position: { x, y, z },
  size,
  ...(label ? { label } : {}),
});

/** 80 nodes at 0.25u lattice in a 2.25×1.75 box (audit4 proven case: 70 pairs < 52px). */
function denseLattice(): PrimitiveObjectSpec[] {
  const objects: PrimitiveObjectSpec[] = [];
  for (let i = 0; i < 80; i++) {
    objects.push(
      sphere(`n${i}`, (i % 10) * 0.25, Math.floor(i / 10) * 0.25, 0, 1)
    );
  }
  return objects;
}

const LONG_PROSE =
  "photosynthesis converts light energy into chemical energy stored in glucose";

export const STRESS_CORPUS: StressCorpusCase[] = [
  {
    id: "dense_80_lattice",
    spec: makeSpec("dense_80_lattice", denseLattice()),
    expect: {
      critical: 0,
      major: 1166, // pairwise I1 envelope intersections on the UNREPAIRED lattice
      minor: 0,
      reasons: ["envelope_intersection"],
    },
    documentedLimitation:
      "The fixture has no relationships → non-graph → identity layout, so 80 " +
      "coincident-lattice spheres render as authored and the gate reports the " +
      "mass I1 breach loudly (1166 pairwise majors; the pipeline emits " +
      "gate_I1_violations + gate_unverified — never a silent pass). This is the " +
      "fail-loudly contract working; a mass-overlap spec cannot pass the gate.",
  },
  {
    id: "size5_1u_spacing",
    spec: makeSpec(
      "size5_1u_spacing",
      [
        sphere("s1", 0, 0, 0, 5),
        sphere("s2", 1, 0, 0, 5),
        sphere("s3", 2, 0, 0, 5),
        sphere("s4", 0, 1, 0, 5),
        sphere("s5", 1, 1, 0, 5),
        sphere("s6", 2, 1, 0, 5),
      ],
      [{ id: "r1", type: "causes", from: "s1", to: "s2" }]
    ),
    expect: {
      critical: 0,
      major: 0, // MUST-FIX 4/5: grid fallback + post-repair lengthening resolve it
      minor: 0,
      reasons: ["layout_repaired", "edge_label_skipped_no_space"],
    },
    documentedLimitation:
      "Gate-clean after repair: the layout's grid-slot reflow (threshold lowered " +
      "to 4 by MUST-FIX 4) spreads the six size-5 nodes and the post-repair " +
      "lengthening (MUST-FIX 5) keeps every edge L >= r_s + r_t + headLen. The " +
      "edge labels are skipped with a reason (edge_label_skipped_no_space).",
  },
  {
    id: "long_labels_25",
    spec: makeSpec(
      "long_labels_25",
      Array.from({ length: 25 }, (_, i) =>
        sphere(`n${i}`, (i % 5) * 2, Math.floor(i / 5) * 2, 0, 1, LONG_PROSE)
      )
    ),
    expect: {
      critical: 0,
      major: 0,
      minor: 0,
      reasons: ["label_truncated_ellipsis"],
    },
    documentedLimitation:
      "All 25 labels are ellipsized to the 288px texture budget (INFO " +
      "label_truncated_ellipsis — never a violation); the remaining sprites " +
      "place collision-free and the canonical framing (perspective distance " +
      "grown to cover every canonical view, Wave-4b) keeps I5 clean.",
  },
  {
    id: "duplicates",
    spec: makeSpec(
      "duplicates",
      [
        { id: "pn1", kind: "process_node", position: { x: -3, y: 0, z: 0 } },
        { id: "ep1", kind: "energy_packet", position: { x: -3, y: 0, z: 0 } },
        sphere("pn2", 0, 0, 0),
        sphere("pn3", 3, 0, 0),
      ],
      [
        { id: "f1", type: "flows_to", from: "pn1", to: "pn2" },
        { id: "f2", type: "flows_to", from: "pn2", to: "pn3" },
      ]
    ),
    expect: {
      critical: 0,
      major: 0, // layout snaps the chained packet to the source surface
      minor: 0,
      reasons: ["layout_repaired", "edge_label_skipped_no_space"],
    },
    documentedLimitation:
      "The pn1/ep1 duplicate is repaired by design (design-1 §1.6 packet snap: " +
      "ep1 lands on pn1's surface at exactly r_s + r_pkt + PATH_CLEARANCE). The " +
      "corpus previously expected this case to FAIL where the pipeline now " +
      "succeeds — the expectation was re-pinned to the actual post-wiring " +
      "contract (MUST-FIX 1).",
  },
  {
    id: "z_only_pair",
    spec: makeSpec("z_only_pair", [
      sphere("a", 0, 1, 0),
      sphere("b", 0, 1, 5),
    ]),
    expect: {
      critical: 0,
      major: 0, // 3D clean (z separates); 2D spread rule applies (P3 parity)
      minor: 0,
      reasons: [],
    },
  },
  {
    id: "deep_groups",
    spec: makeSpec(
      "deep_groups",
      [
        { id: "g1", kind: "group", children: ["g2", "leaf1"] },
        { id: "g2", kind: "group", children: ["g3", "leaf2"] },
        { id: "g3", kind: "group", children: ["g4", "leaf3"] },
        { id: "g4", kind: "group", children: ["leaf4"] },
        sphere("leaf1", -2, 0, 0),
        sphere("leaf2", -1, 0, 0),
        sphere("leaf3", 1, 0, 0),
        sphere("leaf4", 2, 0, 0),
      ] as PrimitiveObjectSpec[],
      [{ id: "c1", type: "contains", from: "g1", to: "leaf1" }]
    ),
    expect: {
      critical: 0,
      major: 0,
      minor: 0,
      reasons: ["relationship_invisible_both_surfaces"],
    },
    documentedLimitation:
      "The `contains` relationship is structural and never drawn on either " +
      "surface — the INFO checker reports it (relationship_invisible_both_" +
      "surfaces), which never flips `ok`. Group opacity propagation is covered " +
      "by the renderer tests (MUST-FIX 3), not by this fixture.",
  },
  {
    id: "hub_8_branches",
    spec: makeSpec(
      "hub_8_branches",
      [
        sphere("hub", 0, 0, 0, 1.2),
        ...Array.from({ length: 8 }, (_, i) => {
          const a = (i / 8) * Math.PI * 2;
          return sphere(`b${i}`, Math.cos(a) * 2.4, Math.sin(a) * 2.4, 0, 1);
        }),
      ],
      Array.from({ length: 8 }, (_, i) => ({
        id: `r${i}`,
        type: "activates" as const,
        from: "hub",
        to: `b${i}`,
      }))
    ),
    expect: {
      critical: 0,
      major: 0, // edge-label density: ≥ 5 skipped → edge_label_suppressed_density
      minor: 0,
      reasons: ["edge_label_suppressed_density", "edge_label_skipped_no_space"],
    },
  },
  {
    id: "short_edges",
    spec: makeSpec(
      "short_edges",
      [sphere("a", 0, 0, 0), sphere("b", 0.6, 0, 0), sphere("c", 1.4, 0, 0)],
      [
        { id: "r1", type: "causes", from: "a", to: "b" }, // 0.6u — head embeds source
        { id: "r2", type: "causes", from: "b", to: "c" }, // 0.8u — head embeds source
      ]
    ),
    expect: {
      critical: 0,
      major: 0, // MUST-FIX 5: post-repair lengthening stretches both edges
      minor: 0,
      reasons: ["layout_repaired", "edge_label_skipped_no_space"],
    },
    documentedLimitation:
      "Both endpoints are directly movable, so the layout's post-repair " +
      "lengthening (MUST-FIX 5) stretches each edge along its axis to " +
      "L >= r_s + r_t + headLen — the arrowhead never embeds the source. The " +
      "edge labels are skipped with a reason (their shaft is too short for a " +
      "label to clear).",
  },
  {
    id: "edge_on_node",
    spec: makeSpec(
      "edge_on_node",
      [
        sphere("a", -3, 1, 0),
        sphere("b", 0, 1, 0),
        sphere("mid", -1.5, 1, 0), // sits ON the a→b segment (audit3 F-06 repro)
      ],
      [{ id: "r1", type: "causes", from: "a", to: "b" }]
    ),
    expect: {
      critical: 0,
      major: 0, // routed detour → I2 clean (raw straight segment would violate)
      minor: 0,
      reasons: ["edge_label_skipped_no_space"],
    },
  },
  {
    id: "outlier_crush",
    spec: makeSpec(
      "outlier_crush",
      [
        ...Array.from({ length: 20 }, (_, i) =>
          sphere(`n${i}`, (i % 5) - 2, Math.floor(i / 5) - 2, 0, 1)
        ),
        sphere("outlier", 400, 0, 0, 1),
      ]
    ),
    expect: {
      critical: 0,
      major: 672, // I5: the 400u outlier cannot fit the clamped perspective frame
      minor: 0,
      reasons: ["content_outside_viewport"],
    },
    documentedLimitation:
      "Non-graph fixture: the perspective distance clamps at 120 while " +
      "(200 + margin)/tan(25°) ≈ 431 would be needed to frame the 400u " +
      "outlier — unframable by design. The 2D surface spreads the cluster " +
      "(design-2 §6.2 F6); the 3D reports the breach loudly (gate_I5_violations " +
      "+ gate_unverified). Authoring stress case, not shipped content.",
  },
];
