import { z } from "zod";
import type {
  ExperimentParameterKey,
  ExperimentParameters,
  SimulationSnapshot,
  TrialRecord,
} from "./experiments";
import { trialRecordSchema } from "./experiments";
import type { RepresentationMode } from "./learner";

export type AdaptationDecision = "accepted" | "rejected" | "modified" | "pending";

/**
 * Structured quick-choice answers for predictions. The deterministic
 * adaptation provider classifies predictions primarily from these keys.
 */
export const PREDICTION_ANSWER_CHOICES = [
  "stays_the_same",
  "slightly_faster",
  "much_faster_nonlinear",
  "slower",
  "stops",
] as const;
export type PredictionAnswerChoice = (typeof PREDICTION_ANSWER_CHOICES)[number];

export const PREDICTION_ANSWER_LABELS: Record<PredictionAnswerChoice, string> = {
  stays_the_same: "It stays about the same",
  slightly_faster: "It gets slightly faster",
  much_faster_nonlinear: "It grows much faster than before",
  slower: "It gets slower",
  stops: "It stops completely",
};

export interface PredictionRecord {
  id: string;
  trialId: string;
  prompt: string;
  answer: string;
  /**
   * Structured answer key chosen from the prediction quick choices, when the
   * learner used one. Free-text answers have null here.
   */
  structuredAnswer: string | null;
  confidence: number | null;
  createdAt: string;
}

export const predictionRecordSchema = z.object({
  id: z.string().min(1),
  trialId: z.string().min(1),
  prompt: z.string(),
  answer: z.string(),
  structuredAnswer: z.string().nullable(),
  confidence: z.number().int().min(1).max(5).nullable(),
  createdAt: z.string().datetime(),
});

export type ConceptStatus = "supported" | "partial" | "uncertain" | "contradicted";

export interface ConceptEvidence {
  conceptId: string;
  status: ConceptStatus;
  evidenceIds: string[];
}

export const conceptEvidenceSchema = z.object({
  conceptId: z.string().min(1),
  status: z.enum(["supported", "partial", "uncertain", "contradicted"]),
  evidenceIds: z.array(z.string()),
});

export const ADAPTATION_PROPOSAL_TYPES = [
  "freeze_variables",
  "slow_animation",
  "show_graph",
  "show_causal_view",
  "reduce_density",
  "compare_trials",
  "ask_prediction_again",
] as const;
export type AdaptationProposalType = (typeof ADAPTATION_PROPOSAL_TYPES)[number];

export interface AdaptationProposal {
  id: string;
  type: AdaptationProposalType;
  /** Plain-language reason shown to the learner. */
  reason: string;
  /** IDs of the session evidence records that triggered this proposal. */
  evidenceIds: string[];
  proposedChanges: Record<string, unknown>;
  decision: AdaptationDecision;
  createdAt: string;
  decidedAt: string | null;
  /**
   * Where this interpretation came from: a hosted structured model ("llm")
   * or the offline deterministic rules ("rules"). Shown in the UI so the
   * learner can always tell AI interpretation apart from the simulation.
   */
  source: "llm" | "rules";
  /** Optional simulation-grounded follow-up question generated by the model. */
  followUpQuestion: string | null;
}

export const adaptationProposalSchema = z.object({
  id: z.string().min(1),
  type: z.enum(ADAPTATION_PROPOSAL_TYPES),
  reason: z.string().min(1),
  evidenceIds: z.array(z.string()),
  proposedChanges: z.record(z.string(), z.unknown()),
  decision: z.enum(["accepted", "rejected", "modified", "pending"]),
  createdAt: z.string().datetime(),
  decidedAt: z.string().datetime().nullable(),
  source: z.enum(["llm", "rules"]).default("rules"),
  followUpQuestion: z.string().nullable().default(null),
});

/**
 * A recorded counterfactual comparison: the original real trial and the
 * hypothetical run that differs in EXACTLY one variable with the same seed.
 * Stored separately from real trials so multi-trial rules and replay never
 * mistake a comparison for a learner-run trial.
 */
export interface CounterfactualRecord {
  originalTrialId: string;
  changedVariable: ExperimentParameterKey;
  original: TrialRecord;
  counterfactual: TrialRecord;
  createdAt: string;
}

export const counterfactualRecordSchema = z.object({
  originalTrialId: z.string().min(1),
  changedVariable: z.enum([
    "absorberPosition",
    "startingNeutrons",
    "materialDensity",
    "absorptionProbability",
    "durationSteps",
    "seed",
  ]),
  original: trialRecordSchema,
  counterfactual: trialRecordSchema,
  createdAt: z.string().datetime(),
});

export interface RepresentationEvent {
  mode: RepresentationMode;
  openedAt: string;
}

export const representationEventSchema = z.object({
  mode: z.enum(["animation", "graph", "equation", "causal", "plain_language"]),
  openedAt: z.string().datetime(),
});

export interface SessionEvidence {
  predictions: PredictionRecord[];
  trials: TrialRecord[];
  representationEvents: RepresentationEvent[];
  adaptationProposals: AdaptationProposal[];
  conceptEvidence: ConceptEvidence[];
  counterfactuals: CounterfactualRecord[];
}

export const sessionEvidenceSchema = z.object({
  predictions: z.array(predictionRecordSchema),
  trials: z.array(trialRecordSchema),
  representationEvents: z.array(representationEventSchema),
  adaptationProposals: z.array(adaptationProposalSchema),
  conceptEvidence: z.array(conceptEvidenceSchema),
  // Optional so pre-counterfactual sessions (and corrupt storage) stay valid.
  counterfactuals: z.array(counterfactualRecordSchema).default([]),
});

export function createEmptySessionEvidence(): SessionEvidence {
  return {
    predictions: [],
    trials: [],
    representationEvents: [],
    adaptationProposals: [],
    conceptEvidence: [],
    counterfactuals: [],
  };
}

export function addTrial(
  evidence: SessionEvidence,
  trial: TrialRecord,
): SessionEvidence {
  return { ...evidence, trials: [...evidence.trials, trial] };
}

export function addPrediction(
  evidence: SessionEvidence,
  prediction: PredictionRecord,
): SessionEvidence {
  return { ...evidence, predictions: [...evidence.predictions, prediction] };
}

export function addRepresentationEvent(
  evidence: SessionEvidence,
  event: RepresentationEvent,
): SessionEvidence {
  return {
    ...evidence,
    representationEvents: [...evidence.representationEvents, event],
  };
}

export function addAdaptationProposal(
  evidence: SessionEvidence,
  proposal: AdaptationProposal,
): SessionEvidence {
  return {
    ...evidence,
    adaptationProposals: [...evidence.adaptationProposals, proposal],
  };
}

export function updateAdaptationProposal(
  evidence: SessionEvidence,
  proposal: AdaptationProposal,
): SessionEvidence {
  return {
    ...evidence,
    adaptationProposals: evidence.adaptationProposals.map((p) =>
      p.id === proposal.id ? proposal : p,
    ),
  };
}

export function addConceptEvidence(
  evidence: SessionEvidence,
  concept: ConceptEvidence,
): SessionEvidence {
  const rest = evidence.conceptEvidence.filter(
    (c) => c.conceptId !== concept.conceptId,
  );
  return { ...evidence, conceptEvidence: [...rest, concept] };
}

export function addCounterfactual(
  evidence: SessionEvidence,
  record: CounterfactualRecord,
): SessionEvidence {
  return {
    ...evidence,
    counterfactuals: [...evidence.counterfactuals, record],
  };
}

/** Parameter keys changed in a trial relative to a prior set of parameters. */
export function diffParameters(
  previous: ExperimentParameters | null,
  current: ExperimentParameters,
): ExperimentParameterKey[] {
  if (!previous) return [];
  return (Object.keys(current) as ExperimentParameterKey[]).filter(
    (key) => previous[key] !== current[key],
  );
}

/** Counts how many distinct variables differ between two parameter sets. */
export function countVariableDiffs(
  previous: ExperimentParameters | null,
  current: ExperimentParameters,
): number {
  return diffParameters(previous, current).length;
}

export function latestSnapshot(
  trial: TrialRecord | null,
): SimulationSnapshot | null {
  if (!trial || trial.snapshots.length === 0) return null;
  return trial.snapshots[trial.snapshots.length - 1];
}
