"use client";

import { useRouter } from "next/navigation";
import {
  TRUST_LABELS,
  type DemoSpecV1,
} from "@/demonstrations/spec/demo-spec";
import { demoStore, type DemoSource } from "@/demonstrations/state/demo-store";

interface DemoSummaryCardProps {
  spec: DemoSpecV1;
  source: DemoSource;
  generatedAt: string;
  /** Return to the ask form with a fresh request. */
  onStartOver: () => void;
}

/**
 * The demonstration summary: trust label, learning objective, main controls,
 * primary limitation, generation source, and the hand-off into the demo page
 * (demoStore.startDemo + router.push("/demos/<id>")).
 */
export function DemoSummaryCard({
  spec,
  source,
  generatedAt,
  onStartOver,
}: DemoSummaryCardProps) {
  const router = useRouter();

  const trustLabel = TRUST_LABELS[spec.trust.level] ?? spec.trust.label;
  const mainControls = spec.controls.slice(0, 4);
  const primaryLimitation = spec.trust.limitations[0];

  const handleEnterDemo = () => {
    demoStore.startDemo(spec, source, generatedAt);
    router.push(`/demos/${spec.id}`);
  };

  return (
    <div className="rounded-2xl border border-white/15 bg-white/5 p-6 text-left backdrop-blur-md">
      <div className="flex flex-wrap items-center gap-2">
        <span className="inline-flex items-center rounded-full border border-teal-400/40 bg-teal-400/10 px-3 py-1 text-xs font-medium text-teal-300">
          {trustLabel}
        </span>
        {source === "offline" ? (
          <span className="inline-flex items-center rounded-full border border-white/20 bg-white/5 px-3 py-1 text-xs font-medium text-gray-300">
            Built from the offline catalog
          </span>
        ) : (
          <span className="inline-flex items-center rounded-full border border-white/20 bg-white/5 px-3 py-1 text-xs font-medium text-gray-300">
            Generated by the demonstration model
          </span>
        )}
      </div>

      <h3 className="mt-4 text-xl font-semibold tracking-tight text-white">
        {spec.title}
      </h3>
      <p className="mt-2 text-base leading-7 text-gray-300">
        {spec.learningObjective}
      </p>

      <h4 className="mt-5 text-sm font-semibold text-white">Main controls</h4>
      <ul className="mt-2 space-y-1.5 text-sm leading-6 text-gray-300">
        {mainControls.map((control) => (
          <li key={control.id} className="flex items-start gap-2">
            <span
              aria-hidden="true"
              className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-400"
            />
            {control.label}
          </li>
        ))}
      </ul>

      {primaryLimitation ? (
        <p className="mt-5 text-xs leading-5 text-gray-400">
          <span className="font-medium text-gray-300">Limitation:</span>{" "}
          {primaryLimitation}
        </p>
      ) : null}

      <div className="mt-6 flex flex-wrap items-center gap-3">
        <button
          type="button"
          onClick={handleEnterDemo}
          className="inline-flex items-center gap-2 rounded-xl bg-teal-500 px-6 py-3 font-semibold text-[#070b14] transition-colors hover:bg-teal-400 focus:outline-none focus-visible:ring-2 focus-visible:ring-teal-300/60"
        >
          Enter demonstration
        </button>
        <button
          type="button"
          onClick={onStartOver}
          className="rounded-xl px-4 py-3 text-sm font-medium text-gray-300 transition-colors hover:bg-white/10 hover:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-teal-300/60"
        >
          Start over
        </button>
      </div>
    </div>
  );
}
